# Generated by Django 2.2.13 on 2022-03-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treenipaivakirja', '0007_ourasleep'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE VIEW treenipaivakirja_harjoitus_vw
            AS
            SELECT 
                h.id          AS id,
                h.user_id     AS user_id,
                a.vuosi       AS vuosi,
                a.kk          AS kk,
                a.kk_nimi     AS kk_nimi,
                a.vko         AS vko,
                a.viikonpaiva_lyh AS viikonpaiva,
                a.vvvvkkpp    AS vvvvkkpp,
                a.pvm         AS pvm,
                h.vuorokaudenaika AS vuorokaudenaika,
                l.laji        AS laji, 
                l.laji_nimi   AS laji_nimi,
                l.laji_ryhma  AS laji_ryhma,
                h.kesto_h     AS kesto_h,
                h.kesto_min   AS kesto_min,
                h.kesto       AS kesto,
                h.keskisyke   AS keskisyke, 
                h.matka       AS matka, 
                h.vauhti_km_h AS vauhti_km_h, 
                h.vauhti_min_km AS vauhti_min_km, 
                h.kalorit     AS kalorit,
                h.nousu       AS nousu,
                h.tuntuma     AS tuntuma,
                h.kommentti   AS kommentti,
                k.kausi       AS kausi
            FROM treenipaivakirja_aika a
                JOIN treenipaivakirja_harjoitus h
                    ON h.aika_id = a.vvvvkkpp
                JOIN treenipaivakirja_laji l
                    ON h.laji_id = l.id
                LEFT JOIN treenipaivakirja_kausi k
                    ON h.user_id = k.user_id
                    AND k.alkupvm <= h.pvm
                    AND k.loppupvm >= h.pvm
        """)
    ]