# Generated by Django 3.2.14 on 2023-07-29 18:09

import django.core.validators
from django.db import migrations, models
import treenipaivakirja.models


class Migration(migrations.Migration):

    dependencies = [
        ('treenipaivakirja', '0007_ourasleep'),
    ]

    operations = [
        migrations.AddField(
            model_name='harjoitus',
            name='polar_exercise_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harjoitus',
            name='reitti',
            field=models.FileField(blank=True, null=True, upload_to=treenipaivakirja.models.user_gpx_path, validators=[django.core.validators.FileExtensionValidator(['gpx'])]),
        ),
    ]
