# Generated by Django 4.2.10 on 2025-07-12 16:22

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('treenipaivakirja', '0008_auto_20230729_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourauser',
            name='access_token',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ourauser',
            name='refresh_token',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='polaruser',
            name='access_token',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
    ]
