# Generated by Django 2.2.13 on 2022-03-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treenipaivakirja', '0008_harjoitusview'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarjoitusView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vuosi', models.IntegerField()),
                ('kk', models.IntegerField()),
                ('kk_nimi', models.CharField(max_length=20)),
                ('vko', models.IntegerField()),
                ('viikonpaiva_lyh', models.CharField(max_length=20)),
                ('pvm', models.DateField()),
                ('vuorokaudenaika', models.IntegerField()),
                ('laji', models.CharField(max_length=10)),
                ('laji_nimi', models.CharField(max_length=50)),
                ('laji_ryhma', models.CharField(max_length=50)),
                ('kesto_h', models.IntegerField()),
                ('kesto_min', models.IntegerField()),
                ('kesto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('keskisyke', models.IntegerField()),
                ('matka', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vauhti_km_h', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vauhti_min_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kalorit', models.IntegerField()),
                ('nousu', models.IntegerField()),
                ('tuntuma', models.IntegerField()),
                ('kommentti', models.CharField(max_length=250)),
                ('kausi', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'treenipaivakirja_harjoitus_vw',
                'managed': False,
            },
        ),
    ]
